parameters:
  - name: name
    default: Test_Bash_macOS
  - name: vmImage
    default: ''
  - name: BuildConfiguration
    default: ''
  - name: Workloads
    default: ''
  - name: Xcode
    default: '/Applications/Xcode_15.1.app'

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      BuildConfiguration: ${{ parameters.BuildConfiguration }}
      Workloads: ${{ parameters.Workloads }}
      Xcode: ${{ parameters.Xcode }}
    steps:
      - task: CmdLine@2
        displayName: 'Set XCode Version'
        inputs:
          script: |
            sudo xcode-select -s $(Xcode)
      - task: UseDotNet@2
        displayName: Install .NET Core SDK
        inputs:
          useGlobalJson: true
      - task: DotNetCoreCLI@2
        condition: ne(variables.Workloads, '')
        displayName: Install workloads
        inputs:
          command: 'custom'
          custom: 'workload'
          arguments: 'install $(Workloads)'
      - task: Bash@3
        displayName: Nuke Target Test
        inputs:
          targetType: filePath
          filePath: ./build.sh
          arguments: --target Test --configuration $(BuildConfiguration) --version-suffix "build$(Build.BuildNumber)"
      - task: PublishTestResults@2
        displayName: Publish Test Results
        inputs:
          testResultsFormat: VSTest
          testResultsFiles: '*.trx'
          searchFolder: $(System.DefaultWorkingDirectory)/artifacts/TestResults
